[package]
name = "duplicate-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6"
futures = "0.3.0"
async-std = "1"
ring = "0.16.20"
data-encoding = "2.3.3"
fuzzy-matcher = "0.3.7"
colored = "2.0.0"
spinners = "4.1.0"
